### ISSUE TITLE
(possible) recent cumulative height limit increases

### ISSUE THREAD

**Issue by ExaInsanity** [HeightLimitMod/HeightLimitMod.github.io#5]
evidence, comprised of 15 to 20 maps, suggests that Hypixel cumulatively incremented height limits by one (with the exception of Graveship, which has been increased by two, but i don't know in which timeframe considering i avoid Graveship if i can). there is no mention of this anywhere in the rotation log, from here downwards; https://hypixel.net/threads/bed-wars-map-rotation-log.4441812/post-35620554; whereas lower bound changes are explicitly listed.

therefore, while i'm working on a pull request to note down the current height limit for maps as i get chances to look at the height limit, i thought i'd bring it up for discussion (mostly because of the Graveship outlier) - is this a known change?

**Comment by pinkulu** [comment]
first im hearing of this, but i had an idea that some maps ware being switched around as there ware like 2 or 1 PRs fixing old maps

**Comment by pinkulu** [comment]
oh wait i think it was you who fixed old maps lmao
